### ISSUE TITLE
Crunch 1.0 (installer) doesn't work but brew 0.9.0 does

### ISSUE THREAD

**Issue by sandrobilbeisi** [chrissimpkins/Crunch#12]
Crunch 1.0 (installer) doesn't work but brew 0.9.0 does
Mac OS X 10.10.5
> 
dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib Referenced from: /Volumes/Crunch Installer/Crunch.app/Contents/Resources/./pngquant Reason: Incompatible library version: pngquant requires version 51.0.0 or later, but libpng16.16.dylib provides version 47.0.0 /Volumes/Crunch Installer/Crunch.app/Contents/Resources/script: line 10: 64882 Trace/BPT trap: 5 ./pngquant --quality=80-98 --skip-if-larger --force --ext -crunch.png "$imagepath" > /dev/null

![screen shot 2018-03-26 at 16 57 47](https://user-images.githubusercontent.com/755824/37914161-dbd8232e-3116-11e8-97cd-21b939667b1a.png)

the older 0.9.0 installed by brew works just fine
![screen shot 2018-03-26 at 16 57 53](https://user-images.githubusercontent.com/755824/37914146-d64478e0-3116-11e8-8d38-27fbaecf4a20.png)

**Comment by chrissimpkins** [comment]
@sandrobilbeisi Thank you very much Sandro!  Sorry for the troubles.  Check out #7 where we are working on this issue.  

Short answer is that as of the changes to the Homebrew cask install script that occurred overnight (in the last 12 hours...) you should not experience this issue with the application when installed through homebrew cask at v1.0.0.  You will still experience it with the dmg installer at v1.0.0 and need to install two pngquant library dependencies.  Sorry! I take full blame... 

As a workaround to use the dmg installer rather than homebrew cask, try the following:

```
$ brew install pngquant
```

Then try using the application again.

Please update with results in #7 if this fixes the issue for you.  Trying to consolidate this to one thread for others who experience the problem.  Thanks for the report and sorry again for the troubles...

**Comment by chrissimpkins** [comment]
@sandrobilbeisi I think that the issue is that there was a transition from statically linked to dynamically linked dependency libraries between v0.10.0+ (including v1.0.0) and v0.9.0 on the pngquant end.  I missed it.  Thanks again for taking the time to report it.  Going to re-compile pngquant with both libraries statically linked during the compile and we can try with the dmg installer again if you are willing to help test this.

**Comment by sandrobilbeisi** [comment]
I solved the problem as you've advised by installing pngquant
> $ brew install pngquant

nb. installation of dependencies (ie rustc ) took an hour ...

**Comment by chrissimpkins** [comment]
@sandrobilbeisi thank you! This is helpful. I will statically link the libraries and see if this does the trick.  I should be providing self contained libraries with the binaries.  This was an oversight.  I must have the dynamically linked libraries installed on my dev system... Thanks for taking the time to help here!
