### ISSUE TITLE
Weird installer

### ISSUE THREAD

**Issue by erusev** [chrissimpkins/Crunch#24]
Is it expected that `make build-dependencies` should produce hundreds of pages like this:

![image](https://user-images.githubusercontent.com/184170/40053353-96908a68-5849-11e8-8658-c945e33c8ec7.png)

...and then create these 2 folders in the user folder:

![image](https://user-images.githubusercontent.com/184170/40052791-8364a728-5847-11e8-9785-7b58719a57f0.png)

**Comment by chrissimpkins** [comment]
Yep! It compiles the zopflipng and pngquant dependencies that are necessary to optimize your png images.  They are installed off of the system PATH in those directories so that you can use any version of the two applications that you like on your PATH. I chose to pin these versions in the project across each of the three tools so that the data that I display on them are valid and they yield the same compression irrespective of the tool that you use.  The lengthy text during the compile is typical output from the C/C++ compiler.  I can update the docs to warn users that this will happen.   Thanks for pointing it out.

**Comment by erusev** [comment]
Thanks, I appreciate the quick response!

**Comment by chrissimpkins** [comment]
Enjoy! Let me know if you come across any problems when you have a chance to use it.  Would greatly appreciate any feedback that you have.

**Comment by chrissimpkins** [comment]
I added further detail about the installation process in the docs to address your concerns here.  Mind having a look at https://github.com/chrissimpkins/Crunch/blob/master/docs/EXECUTABLE.md#what-happens-during-the-installation? If you feel that this addresses your concern about the install process, please close the issue.  Thanks again for your feedback.
