### ISSUE TITLE
Docker: installation problem

### ISSUE THREAD

**Issue by f3l1x** [chrissimpkins/Crunch#69]
**Describe the bug**
Cannot install crunch in Docker/Debian.

**To Reproduce**

```
FROM dockette/stretch

RUN apt-get update && \
    apt-get dist-upgrade -y

RUN apt-get install -y git make curl gcc g++ sudo libpng-dev

WORKDIR /srv

RUN git clone https://github.com/chrissimpkins/Crunch.git /srv

RUN make build-dependencies
RUN make install-executable
```

**Expected behavior**
Proper installation.

**Screenshots and/or Log Text**
![image](https://user-images.githubusercontent.com/538058/45263589-24936400-b42c-11e8-8706-33ce8b337b66.png)

**Desktop (please complete the following information):**
 - OS:  on macOS

**Additional context**
nope

**Comment by chrissimpkins** [comment]
Sorry!  The install scripts were not designed with containerization in mind.  It appears that you are getting hung up at the libpng unpacking step here 

https://github.com/chrissimpkins/Crunch/blob/ee00d14be24f13e0339637aff6e4cb17c1b54f42/src/install-dependencies.sh#L44

Here is what I see when I perform the libpng pull manually:

```
$ curl -L -O "https://sourceforge.net/projects/libpng/files/libpng16/1.6.34/libpng-1.6.34.tar.xz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15749  100 15749    0     0  25525      0 --:--:-- --:--:-- --:--:-- 25483
100 15825  100 15825    0     0  19441      0 --:--:-- --:--:-- --:--:-- 19441
100   351  100   351    0     0    278      0  0:00:01  0:00:01 --:--:--   278
100  974k  100  974k    0     0   376k      0  0:00:02  0:00:02 --:--:--  973k


$ ls -la
total 1952
drwxr-xr-x   3 ces  staff      96 Sep  9 10:24 .
drwxr-xr-x  13 ces  staff     416 Sep  9 10:23 ..
-rw-r--r--   1 ces  staff  997968 Sep  9 10:24 libpng-1.6.34.tar.xz
```

When `tar` tries to unpack that tar.xz compressed archive file in your container, it is not finding the tar.xz file on the expected path so there is no directory path `libpng-1.6.34` available to `cd` into in this line:

https://github.com/chrissimpkins/Crunch/blob/ee00d14be24f13e0339637aff6e4cb17c1b54f42/src/install-dependencies.sh#L46

It looks like there is a path problem at play.  Are you able to display the paths in your container after the fail so that we can see where `curl` is placing the archive file that is pulled?  The expected paths can be found in constants at the head of the `src/install-dependencies.sh` script in the Crunch repository.
